# Generated by Django 3.2 on 2024-02-13 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default=None)),
                ('status', models.CharField(choices=[('SELECTED', 'Selected'), ('UNSELECTED', 'UnSelected')], default='UNSELECTED', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
