# Generated by Django 3.2 on 2024-02-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_contentdata_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contentdata',
            managers=[
            ],
        ),
    ]
