# Generated by Django 3.2 on 2024-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_contentdata_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdata',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
